version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  hello: circleci/hello-build@0.0.7 # circleci/buildpack-deps Docker イメージを使います

workflows:
  "Hello Workflow":
      jobs:
        - hello/hello-build
