jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - slack/notify:
          color: '#42e2f4'
          message: "Hey ${CIRCLE_USERNAME}, ${CIRCLE_JOB}, ${CIRCLE_BUILD_URL}"
          webhook: '${SLACK_WEBHOOK}'
      - run:
          command: |
            echo "hello world~"

orbs:
  slack: circleci/slack@3.4.2
version: 2.1
workflows:
  my-workflow:
    jobs:
    - build 
