version: 2.1

jobs:
  build:
    docker:
      - image: <docker image>
    steps:
      - run: exit 0
      - slack/status:
          fail_only: true
          mentions: 'kosei'
          only_for_branches: only_for_branches
          webhook: webhook
orbs:
  slack: circleci/slack@3.4.2
version: 2.1
